### PR TITLE
getMotionDetectConfig1

### PR DESCRIPTION
**Pull request by rooi**
My C2 Foscam gives an empty reply to getMotionDetectConfig and others have reported the same problem. Fiscal Helpdesk gave me the getMotionDetectConfig1 command which works for the c2 at least

### CODE REVIEW

**Comment by lightswitch05** [comment]
Hey @rooi thank you for the pull request. I'll be happy to merge this in if you can provide some unit test

**Comment by rooi** [comment]
Hey, I've added some smiliar code in you AV.spec file, but I'm not sure how to use/test it. Could you please give some pointers?

Note I'm still starting nodejs programming, so please consider this if this seems obvious for you

**Comment by lightswitch05** [comment]
The tests look good. Assuming you followed the development setup section in the README file you can run them locally on your computer simply by running `gulp`. Of course you can also just let Travis-Ci run test after you commit too.

It looks like all your tests ran fine, it just complaining about your code style:

```
lib/AV.js
  574:1  error  Trailing spaces not allowed  no-trailing-spaces
test/AV.spec.js
  394:1  error  Trailing spaces not allowed  no-trailing-spaces
  400:1  error  Trailing spaces not allowed  no-trailing-spaces
  407:1  error  Trailing spaces not allowed  no-trailing-spaces
```

Just remove all those trailing spaces and everything should pass. Depending on what editor you use, you can probably configure it to remove trailing whitespaces for you

**Comment by rooi** [comment]
Ah I see, thanks for explaining. I've removed all the whitespace and the functions work well in combination with the homebridge-foscam plugin and my C2.

**Comment by lightswitch05** [comment]
Merged and released to v0.3.0. Thanks!

**Pull request merged**
