### PR TITLE
fix snapPicture and snapPicture2

### PR DESCRIPTION
**Pull request by vitosamson**
@lightswitch05 can you merge and publish to npm when you get a chance?

### CODE REVIEW

**Comment by lightswitch05** [comment]
I won't have my laptop for a couple days. I was a little concerned about the binary picture data going through the `Foscam.parseResponse` function. I guess it doesn't cause any problems?

**Comment by vitosamson** [comment]
Hmm yeah there does seem to be an issue with that. With `getRaw` the response is:

```
<CGI_Result>
    <result>-3</result>
</CGI_Result>
```

With `get` it returns what looks like jpeg data but the data is corrupt or something. I'll investigate a bit more.

**Comment by vitosamson** [comment]
Alright figured it out. Two things - `snapPicture` and `snapPicture2` weren't passing the cgi command correctly to `getRaw`, and we need to pass an `{ encoding: null }` option to request-promise in order to get the jpeg data back correctly.

Last commit should fix all that.

**Comment by lightswitch05** [comment]
:thumbsup: I think you have access to the npm project if you need to release before I get back to a laptop

**Comment by lightswitch05** [comment]
:tada: Merged and released!

**Pull request merged**
